name: Build and Deploy React

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Vite app
      run: npm run build
    
    - name: Build Docker Image
      run: |
        docker build -t alegnta/kchds-front:latest .
        echo "rn3B6fAAYX.!xZV" | docker login --username alegnta --password-stdin

    - name: Push Docker Image
      run: docker push alegnta/kchds-front:latest
